services:
  # Frontend service
  - type: web
    name: secret-santa-frontend
    env: static
    buildCommand: cd frontend && pnpm install && pnpm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  # Backend service
  - type: web
    name: secret-santa-backend
    env: node
    buildCommand: cd backend && pnpm install && pnpm run build
    startCommand: cd backend && pnpm run start:prod
    envVars:
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
