services:
  - type: web
    name: Frontend
    runtime: static
    repo: https://github.com/larsniet/secret_santa
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_STRIPE_PUBLIC_KEY
        sync: false
    buildCommand: pnpm i && pnpm build
    staticPublishPath: build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - www.plansecretsanta.com
      - plansecretsanta.com
    rootDir: frontend
  - type: web
    name: Backend
    runtime: node
    repo: https://github.com/larsniet/secret_santa
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
    region: oregon
    buildCommand: cd backend && pnpm i && pnpm build
    startCommand: cd backend && pnpm i --prod && node dist/main
    domains:
      - elves.plansecretsanta.com
    rootDir: .
version: "1"
